name: Workflow
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # Automatycznie raz w tygodniu (w każdą niedzielę o północy)
  workflow_dispatch: # Ręcznie przez użytkownika

jobs:
  build:
    runs-on: windows-latest # Ustawienie domyślnego serwera Windows

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x" # Wybierz wersję Pythona, którą chcesz zainstalować

    - name: Install dependencies
      run: .\installResources.bat
      

    - name: Build .exe
      run: pyinstaller --onefile index.py

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: program.exe
        path: path/do/tworzonego/pliku.exe # Zastąp ścieżką do tworzonego pliku .exe
